### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by dwidoo** [federicotorrielli/BetterWhisperX#8]
We have this issue : https://github.com/m-bain/whisperX/issues/979
Maybe you can update to 3.3.0 version to solve it?

**Comment by federicotorrielli** [comment]
The issue was already fixed before on this repo, two weeks ago. Please re-install betterwhisperx.

**Comment by dwidoo** [comment]
OK but I still have a new 403 http error today with this line : 
`model = whisperx.load_model("large-v3", device, compute_type="float16")
`
and no error when trying with whisperx 3.3.0 instead of BetterWhisperX

**Comment by federicotorrielli** [comment]
try now to uninstall and reinstall betterwhisperx
